name: Build and Test
on: [push, pull_request]
jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.24", "1.25"]
    steps:
      - name: Check out source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ matrix.go }}
      - name: Install Linters
        run: "go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.4.0"
      - name: Test
        run: |
          sh ./run_tests.sh
